---
title: "Tidy Data"
output: github_document
---
```{r setup, echo = FALSE, message=FALSE}
library(tidyverse)
library(readxl)
library(haven)
```

This document will show how to tidy data.

```{r}
 pulse_df = 
   read_sas("data/public_pulse_data.sas7bdat") |>  
   janitor::clean_names()
```

```{r}
 pulse_tidy_df = 
  pulse_df |> 
  pivot_longer(
    cols = bdi_score_bl: bdi_score_12m,
    names_to = "visit",
    values_to = "bdi_score",
    names_prefix = "bdi_score_"
  ) |> 
  mutate(
    visit = replace(visit, visit == "bl", "00m")
  ) |> 
  relocate(id, visit)
   
```

combine 2 steps into 1
using pipe to make the code clearer and easy to understand
```{r}
 pulse_df = 
   read_sas("data/public_pulse_data.sas7bdat") |>  
   janitor::clean_names() |> 
   pivot_longer(
    cols = bdi_score_bl: bdi_score_12m,
    names_to = "visit",
    values_to = "bdi_score",
    names_prefix = "bdi_score_"
  ) |> 
  mutate(
    visit = replace(visit, visit == "bl", "00m")
  ) |> 
  relocate(id, visit)
```


Do one more example.

```{r}
 litters_df = 
   read_csv("data/FAS_litters.csv", na = c("NA",".","")) |>    
   janitor::clean_names() |> 
   pivot_longer(
    cols = gd0_weight:gd18_weight,
    names_to = "gd_time",
    values_to = "weight"
    )
 ```  
   
   
   

    names_prefix = "bdi_score_"
  ) |> 
  
```




